[build]
  publish = "out"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Form processing
[forms]
  [forms.contact-general]
  [forms.contact-speaking]  
  [forms.contact-podcast]